import crypto from "node:crypto";
import { nanoid } from "nanoid";
import { db, runImmediateTransaction } from "./db.js";
import type { DatabaseSync } from "node:sqlite";
import { QUESTION_BANK_SHA256, QUESTION_SET_VERSION, REPORT_VERSION, SCORING_VERSION, buildGoalFitFreeResult, buildGoalFitReport, normalizeGoalFitAnswers } from "./goalFitDomain/index.js";
import type { CompanyType, RoleType } from "./goalFitDomain/goalFitTypes.js";

export class AssessmentStoreError extends Error { constructor(readonly code: "IDEMPOTENCY_CONFLICT" | "ASSESSMENT_STORE_FAILED") { super(code); } }
function key(): Buffer { const source = process.env.ASSESSMENT_DATA_ENCRYPTION_KEY ?? ""; if (!/^[A-Za-z0-9+/]+={0,2}$/.test(source) || source.length % 4 !== 0) throw new AssessmentStoreError("ASSESSMENT_STORE_FAILED"); const raw = Buffer.from(source, "base64"); if (raw.length !== 32) throw new AssessmentStoreError("ASSESSMENT_STORE_FAILED"); return raw; }
export function encryptAssessmentData(value: unknown): string { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", key(), iv); const data = Buffer.concat([cipher.update(JSON.stringify(value), "utf8"), cipher.final()]); return `v1.${Buffer.concat([iv, cipher.getAuthTag(), data]).toString("base64")}`; }
export function decryptAssessmentData<T>(value: string): T { if (!value.startsWith("v1.")) throw new Error("Invalid ciphertext"); const packed = Buffer.from(value.slice(3), "base64"); if (packed.length < 29) throw new Error("Invalid ciphertext"); const decipher = crypto.createDecipheriv("aes-256-gcm", key(), packed.subarray(0, 12)); decipher.setAuthTag(packed.subarray(12, 28)); return JSON.parse(Buffer.concat([decipher.update(packed.subarray(28)), decipher.final()]).toString("utf8")) as T; }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value as object).sort().map(key => `${JSON.stringify(key)}:${stable((value as Record<string, unknown>)[key])}`).join(",")}}`; return JSON.stringify(value); }
function digest(value: unknown): string { return crypto.createHash("sha256").update(stable(value)).digest("hex"); }
function external(prefix: "asm" | "rpt"): string { return `${prefix}_${crypto.randomBytes(24).toString("base64url")}`; }
export function canonicalSubmission(input: { targetCompany: CompanyType; targetRole: RoleType; selectedQuestionIds: string[]; answers: Array<{questionId:string;optionId:string}> }) { const answers = normalizeGoalFitAnswers(input); return { targetCompany: input.targetCompany, targetRole: input.targetRole, questionSetVersion: QUESTION_SET_VERSION, answers: input.selectedQuestionIds.map(questionId => ({ questionId, optionId: answers[questionId] })) }; }
export function canonicalSubmissionHash(input: { targetCompany: CompanyType; targetRole: RoleType; selectedQuestionIds: string[]; answers: Array<{questionId:string;optionId:string}> }): string { return digest(canonicalSubmission(input)); }
export function createCompletedAssessmentSnapshot(input: { platformIdentityId: string; visitorId: string; submissionId: string; targetCompany: CompanyType; targetRole: RoleType; selectedQuestionIds: string[]; answers: Array<{questionId:string;optionId:string}> }, fault?: "beforeAssessment" | "beforeSnapshot") {
  const canonical = canonicalSubmission(input); const answers = Object.fromEntries(canonical.answers.map(answer => [answer.questionId, answer.optionId])); const report = buildGoalFitReport({ targetCompany: input.targetCompany, targetRole: input.targetRole, answers }); const freeResult = buildGoalFitFreeResult({ targetCompany: input.targetCompany, targetRole: input.targetRole, answers }); const payload = { ...canonical, scores: report.scores, questionBankHash: QUESTION_BANK_SHA256, scoringVersion: SCORING_VERSION }; const payloadHash = digest(canonical); // payload_hash is the canonical submission hash, never derived scores/report.
  return runImmediateTransaction(() => { const existing = db.prepare("SELECT a.id,a.assessment_id,r.report_snapshot_id,r.free_result_json,a.payload_hash FROM assessments a JOIN report_snapshots r ON r.assessment_row_id=a.id WHERE a.platform_identity_id=? AND a.submission_id=?").get(input.platformIdentityId, input.submissionId) as any; if (existing) { if (existing.payload_hash !== payloadHash) throw new AssessmentStoreError("IDEMPOTENCY_CONFLICT"); return { assessmentId: existing.assessment_id, reportSnapshotId: existing.report_snapshot_id, freeResult: JSON.parse(existing.free_result_json), idempotent: true }; } if (fault === "beforeAssessment") throw new AssessmentStoreError("ASSESSMENT_STORE_FAILED"); const now = new Date().toISOString(), assessmentId = external("asm"), reportSnapshotId = external("rpt"); const inserted = db.prepare("INSERT INTO assessments (assessment_id,platform_identity_id,visitor_id,submission_id,target_company,target_role,question_set_version,question_bank_hash,scoring_version,payload_ciphertext,payload_hash,status,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(assessmentId,input.platformIdentityId,input.visitorId,input.submissionId,input.targetCompany,input.targetRole,QUESTION_SET_VERSION,QUESTION_BANK_SHA256,SCORING_VERSION,encryptAssessmentData(payload),payloadHash,"completed",now,now,now); if (fault === "beforeSnapshot") throw new AssessmentStoreError("ASSESSMENT_STORE_FAILED"); db.prepare("INSERT INTO report_snapshots (report_snapshot_id,assessment_row_id,report_version,free_result_json,full_report_ciphertext,full_report_hash,created_at) VALUES (?,?,?,?,?,?,?)").run(reportSnapshotId,inserted.lastInsertRowid,REPORT_VERSION,stable(freeResult),encryptAssessmentData(report),digest(report),now); return { assessmentId, reportSnapshotId, freeResult, idempotent: false }; });
}
function publicRow(row: any) { return row ? { assessmentId: row.assessment_id, reportSnapshotId: row.report_snapshot_id, freeResult: JSON.parse(row.free_result_json), completedAt: row.completed_at, versions: { questionSetVersion: row.question_set_version, scoringVersion: row.scoring_version, reportVersion: row.report_version } } : null; }
export function getAssessmentFreeResult(assessmentId: string, platformIdentityId: string) { return publicRow(db.prepare("SELECT a.assessment_id,r.report_snapshot_id,r.free_result_json,a.completed_at,a.question_set_version,a.scoring_version,r.report_version FROM assessments a JOIN report_snapshots r ON r.assessment_row_id=a.id WHERE a.assessment_id=? AND a.platform_identity_id=?").get(assessmentId,platformIdentityId)); }
export function getLatestAssessment(platformIdentityId: string) { return publicRow(db.prepare("SELECT a.assessment_id,r.report_snapshot_id,r.free_result_json,a.completed_at,a.question_set_version,a.scoring_version,r.report_version,a.id FROM assessments a JOIN report_snapshots r ON r.assessment_row_id=a.id WHERE a.platform_identity_id=? ORDER BY a.completed_at DESC,a.id DESC LIMIT 1").get(platformIdentityId)); }
export function decryptFullReport(reportSnapshotId: string, connection: DatabaseSync = db) { const row = connection.prepare("SELECT full_report_ciphertext FROM report_snapshots WHERE report_snapshot_id=?").get(reportSnapshotId) as any; return row ? decryptAssessmentData(row.full_report_ciphertext) : null; }
