import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
const file=`data/payment-order-migration-${Date.now()}.db`;process.env.GOAL_FIT_DB_PATH=file;
const { initializeDatabase,db,databasePath,migrateGoalFitPendingUniqueIndex }=await import("./db.js");
try{initializeDatabase();const names=()=>new Set((db.prepare("PRAGMA table_info(orders)").all() as any[]).map(x=>x.name));for(const name of ["platformIdentityId","assessmentId","reportSnapshotId","orderPurpose","expiresAt"])assert.ok(names().has(name));const indexes=(db.prepare("PRAGMA index_list(orders)").all() as any[]).map(x=>x.name);for(const name of ["idx_orders_platform_identity","idx_orders_assessment","idx_orders_report_snapshot","uq_orders_goal_fit_pending"])assert.ok(indexes.includes(name));initializeDatabase();assert.equal((db.prepare("SELECT COUNT(*) AS count FROM sqlite_master WHERE type='index' AND name='uq_orders_goal_fit_pending'").get() as any).count,1);
const legacy=new DatabaseSync(":memory:");legacy.exec(`CREATE TABLE orders (id TEXT PRIMARY KEY, platformIdentityId TEXT, assessmentId TEXT, orderPurpose TEXT, status TEXT); CREATE UNIQUE INDEX uq_orders_goal_fit_pending ON orders (platformIdentityId, assessmentId, orderPurpose);`);legacy.prepare("INSERT INTO orders VALUES (?, ?, ?, ?, ?)").run("legacy", "identity", "assessment", "goal_fit_full_report", "paid");migrateGoalFitPendingUniqueIndex(legacy);const sql=(legacy.prepare("SELECT sql FROM sqlite_master WHERE type='index' AND name='uq_orders_goal_fit_pending'").get() as any).sql as string;assert.match(sql,/where orderpurpose = 'goal_fit_full_report'/i);legacy.close();
console.log("Goal Fit miniapp payment order migration tests passed.");}finally{db.close();for(const x of ["","-wal","-shm"])try{fs.rmSync(`${databasePath}${x}`,{force:true})}catch{}}
