import assert from "node:assert/strict";import crypto from "node:crypto";
process.env.GOAL_FIT_DB_PATH=`data/privacy-${Date.now()}.db`;process.env.NODE_ENV="test";process.env.WECHAT_MINIAPP_APP_ID="wx";process.env.MINIAPP_IDENTITY_ENCRYPTION_KEY=Buffer.alloc(32,41).toString("base64");process.env.ASSESSMENT_DATA_ENCRYPTION_KEY=Buffer.alloc(32,42).toString("base64");
const {app,setAssessmentStoreForTest,resetAssessmentRateLimitForTest}=await import("./index.js"),{db}=await import("./db.js"),{AssessmentStoreError}=await import("./assessmentStore.js"),{createWechatMiniappSession}=await import("./miniappIdentity.js"),{selectGoalFitQuestions}=await import("./goalFitDomain/index.js");
const server=app.listen(0),base=`http://127.0.0.1:${(server.address() as any).port}`,q=selectGoalFitQuestions("D","PM"),token=(await createWechatMiniappSession({code:"TEST_OPENID_SECRET",visitorId:"visitor_12345678"})).sessionToken,submissionId="sub_PRIVACY_SECRET_123456",payload={submissionId,targetCompany:"D",targetRole:"PM",selectedQuestionIds:q.map(x=>x.id),answers:q.map(x=>({questionId:x.id,optionId:x.options[0].id}))},logs:string[]=[],original={log:console.log,info:console.info,warn:console.warn,error:console.error};
for(const key of Object.keys(original) as Array<keyof typeof original>) (console as any)[key]=(...args:any[])=>logs.push(args.map(String).join(" "));
const request=async(path:string,init:RequestInit={})=>{const r=await fetch(`${base}${path}`,init);const body=await r.json();return {status:r.status,body,headers:r.headers}};
const forbidden=["answers","selectedQuestionIds","scores","detailedScores","fullReport","payloadHash","fullReportHash","payloadCiphertext","fullReportCiphertext","platformIdentityId","visitorId","miniappSessionId","sessionToken","tokenHash","openid","unionid","internalId"];
function scan(value:any){const text=JSON.stringify(value);for(const key of forbidden) assert.equal(text.includes(`\"${key}\"`),false,`leaked ${key}`);for(const secret of [token,submissionId,"TEST_OPENID_SECRET","TEST_SQLITE_ERROR_SECRET"]) assert.equal(text.includes(secret),false,"leaked sensitive value");}
try{let r=await request("/api/miniapp/goal-fit/assessments/complete",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(payload)});assert.equal(r.status,200);scan(r.body);const assessmentId=r.body.assessmentId;r=await request(`/api/miniapp/goal-fit/assessments/${assessmentId}/free-result`,{headers:{authorization:`Bearer ${token}`}});assert.equal(r.status,200);scan(r.body);r=await request("/api/miniapp/goal-fit/assessments/latest",{headers:{authorization:`Bearer ${token}`}});assert.equal(r.status,200);scan(r.body);
 const expired=(await createWechatMiniappSession({code:"expired-session",visitorId:"visitor_87654321"})).sessionToken;db.prepare("UPDATE miniapp_sessions SET expires_at=? WHERE token_hash=?").run(new Date(Date.now()-1).toISOString(),crypto.createHash("sha256").update(expired).digest("hex"));const errors=[await request("/api/miniapp/goal-fit/assessments/complete",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:"{}"}),await request("/api/miniapp/goal-fit/assessments/latest"),await request("/api/miniapp/goal-fit/assessments/latest",{headers:{authorization:`Bearer ${expired}`}}),await request("/api/miniapp/goal-fit/assessments/asm_missing_12345678/free-result",{headers:{authorization:`Bearer ${token}`}})];
 setAssessmentStoreForTest(()=>{throw new AssessmentStoreError("IDEMPOTENCY_CONFLICT")});resetAssessmentRateLimitForTest();errors.push(await request("/api/miniapp/goal-fit/assessments/complete",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({...payload,submissionId:"sub_privacy_conflict_123456"})}));
 setAssessmentStoreForTest(()=>{const e:any=new Error("TEST_SQLITE_ERROR_SECRET");throw e;});resetAssessmentRateLimitForTest();errors.push(await request("/api/miniapp/goal-fit/assessments/complete",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({...payload,submissionId:"sub_privacy_failure_123456"})}));setAssessmentStoreForTest(null);resetAssessmentRateLimitForTest();for(let i=0;i<11;i++) errors.push(await request("/api/miniapp/goal-fit/assessments/complete",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({...payload,submissionId:`sub_privacy_rate_${String(i).padStart(8,"0")}`})}));
 for(const result of errors){scan(result.body);if(result.status>=400)assert.deepEqual(Object.keys(result.body),["error"]);}assert.deepEqual(errors.map(x=>x.status).slice(0,6),[400,401,401,404,409,500]);assert.equal(errors.at(-1)?.status,429);for(const secret of [token,submissionId,"TEST_OPENID_SECRET","TEST_SQLITE_ERROR_SECRET","TEST_FULL_REPORT_SECRET"]) assert.equal(logs.join("\n").includes(secret),false);console.log=original.log;console.log("Goal Fit assessment privacy route tests passed.");
}finally{Object.assign(console,original);setAssessmentStoreForTest(null);resetAssessmentRateLimitForTest();server.close();}
