import assert from "node:assert/strict";
process.env.GOAL_FIT_DB_PATH = `data/assessment-store-${Date.now()}.db`; process.env.ASSESSMENT_DATA_ENCRYPTION_KEY = Buffer.alloc(32, 23).toString("base64");
const { initializeDatabase, db } = await import("./db.js"); initializeDatabase(); initializeDatabase();
db.prepare("INSERT INTO platform_identities (id,platform,app_id,openid_ciphertext,openid_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").run("identity-a", "wechat_miniapp", "wx-test", "v1.test", "hash-a", new Date().toISOString(), new Date().toISOString());
const { canonicalSubmissionHash, createCompletedAssessmentSnapshot, decryptAssessmentData, decryptFullReport, encryptAssessmentData, getAssessmentFreeResult, getLatestAssessment } = await import("./assessmentStore.js");
const { selectGoalFitQuestions } = await import("./goalFitDomain/index.js");
const questions = selectGoalFitQuestions("D", "PM"); const input = { platformIdentityId: "identity-a", visitorId: "visitor_12345678", submissionId: "sub_test_one", targetCompany: "D" as const, targetRole: "PM" as const, selectedQuestionIds: questions.map(q => q.id), answers: questions.map(q => ({ questionId: q.id, optionId: q.options[0].id })) };
const cipherA = encryptAssessmentData({ value: "safe" }), cipherB = encryptAssessmentData({ value: "safe" }); assert.notEqual(cipherA, cipherB); assert.deepEqual(decryptAssessmentData(cipherA), { value: "safe" }); assert.throws(() => decryptAssessmentData(`${cipherA.slice(0, -1)}x`));
const savedKey = process.env.ASSESSMENT_DATA_ENCRYPTION_KEY; process.env.ASSESSMENT_DATA_ENCRYPTION_KEY = "not base64!"; assert.throws(() => encryptAssessmentData({})); process.env.ASSESSMENT_DATA_ENCRYPTION_KEY = Buffer.alloc(31, 1).toString("base64"); assert.throws(() => encryptAssessmentData({})); process.env.ASSESSMENT_DATA_ENCRYPTION_KEY = savedKey;
const created = createCompletedAssessmentSnapshot(input); assert.match(created.assessmentId, /^asm_[A-Za-z0-9_-]+$/); assert.match(created.reportSnapshotId, /^rpt_[A-Za-z0-9_-]+$/); const repeated = createCompletedAssessmentSnapshot({ ...input, answers: [...input.answers].reverse() }); assert.equal(repeated.assessmentId, created.assessmentId); assert.throws(() => createCompletedAssessmentSnapshot({ ...input, answers: [{ ...input.answers[0], optionId: questions[0].options[1].id }, ...input.answers.slice(1)] }));
assert.deepEqual(getAssessmentFreeResult(created.assessmentId, "identity-a")?.freeResult, created.freeResult); assert.equal(getAssessmentFreeResult(created.assessmentId, "identity-b"), null); assert.equal(getLatestAssessment("identity-a")?.assessmentId, created.assessmentId); assert.ok(decryptFullReport(created.reportSnapshotId));
const row = db.prepare("SELECT payload_ciphertext FROM assessments WHERE assessment_id=?").get(created.assessmentId) as { payload_ciphertext: string }; assert.equal(row.payload_ciphertext.includes(JSON.stringify(input.answers)), false);
assert.equal(canonicalSubmissionHash(input), canonicalSubmissionHash({ ...input, answers: [...input.answers].reverse().map(answer => ({ optionId: answer.optionId, questionId: answer.questionId })) }));
for (const fault of ["beforeAssessment", "beforeSnapshot"] as const) { assert.throws(() => createCompletedAssessmentSnapshot({ ...input, submissionId: `sub_${fault}` }, fault)); assert.equal((db.prepare("SELECT count(*) AS count FROM assessments WHERE submission_id=?").get(`sub_${fault}`) as { count: number }).count, 0); }
const snapshotCount = (db.prepare("SELECT count(*) AS count FROM report_snapshots").get() as { count: number }).count; assert.equal(snapshotCount, 1); assert.throws(() => db.prepare("INSERT INTO report_snapshots (report_snapshot_id,assessment_row_id,report_version,free_result_json,full_report_ciphertext,full_report_hash,created_at) VALUES (?,?,?,?,?,?,?)").run("rpt_duplicate", 1, "v", "{}", "v1.x", "x", new Date().toISOString()));
console.log("Goal Fit assessment store tests passed.");
