import assert from "node:assert/strict";
import fs from "node:fs";
process.env.GOAL_FIT_DB_PATH=`data/payment-status-${Date.now()}.db`;
const {db,databasePath,initializeDatabase}=await import("./db.js");
const {createOrReuseGoalFitPaymentOrder,GOAL_FIT_PAYMENT_ORDER_TTL_MS,GoalFitPaymentOrderError}=await import("./goalFitMiniappPaymentOrderStore.js");
const now=new Date("2026-01-03T00:00:00.000Z");
function count(){return Number((db.prepare("SELECT COUNT(*) count FROM orders").get() as any).count)}
try{initializeDatabase();const i="identity_status",a="asm_status";db.prepare("INSERT INTO platform_identities (id,platform,app_id,openid_ciphertext,openid_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").run(i,"wechat_miniapp","wx","cipher","hash",now.toISOString(),now.toISOString());db.prepare("INSERT INTO assessments (assessment_id,platform_identity_id,visitor_id,submission_id,target_company,target_role,question_set_version,question_bank_hash,scoring_version,payload_ciphertext,payload_hash,status,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(a,i,"v","sub_status","D","PM","q","h","s","p","ph","completed",now.toISOString(),now.toISOString(),now.toISOString());const ar=db.prepare("SELECT id FROM assessments WHERE assessment_id=?").get(a) as any;db.prepare("INSERT INTO report_snapshots (report_snapshot_id,assessment_row_id,report_version,free_result_json,full_report_ciphertext,full_report_hash,created_at) VALUES (?,?,?,?,?,?,?)").run("rpt_status",ar.id,"r","{}","c","h",now.toISOString());const first=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now});const reused=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now:new Date(now.getTime()+1)});assert.equal(reused.reused,true);db.prepare("UPDATE orders SET expiresAt=? WHERE id=?").run(now.toISOString(),first.orderId);const replacement=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now});assert.equal(replacement.reused,false);assert.notEqual(replacement.orderId,first.orderId);assert.equal(count(),2);assert.equal((db.prepare("SELECT status FROM orders WHERE id=?").get(first.orderId) as any).status,"expired");db.prepare("UPDATE orders SET status='paid' WHERE id=?").run(replacement.orderId);assert.throws(()=>createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now}), (e:unknown)=>e instanceof GoalFitPaymentOrderError&&e.code==="ALREADY_PURCHASED");assert.equal(count(),2);assert.equal(replacement.expiresAt,new Date(now.getTime()+GOAL_FIT_PAYMENT_ORDER_TTL_MS).toISOString());
// failed and closed histories remain immutable while a new pending order is created.
db.prepare("UPDATE orders SET status='failed' WHERE id=?").run(first.orderId);db.prepare("UPDATE orders SET status='closed' WHERE id=?").run(replacement.orderId);const beforeAssessment=db.prepare("SELECT * FROM assessments WHERE assessment_id=?").get(a);const beforeSnapshot=db.prepare("SELECT * FROM report_snapshots WHERE report_snapshot_id=?").get("rpt_status");const afterHistory=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now});assert.equal(afterHistory.reused,false);assert.equal(count(),3);assert.equal((db.prepare("SELECT status FROM orders WHERE id=?").get(first.orderId) as any).status,"failed");assert.equal((db.prepare("SELECT status FROM orders WHERE id=?").get(replacement.orderId) as any).status,"closed");assert.deepEqual(db.prepare("SELECT * FROM assessments WHERE assessment_id=?").get(a),beforeAssessment);assert.deepEqual(db.prepare("SELECT * FROM report_snapshots WHERE report_snapshot_id=?").get("rpt_status"),beforeSnapshot);
// An expired replacement is atomic: an INSERT failure restores the old pending row.
db.prepare("UPDATE orders SET expiresAt=? WHERE id=?").run(now.toISOString(),afterHistory.orderId);const old=db.prepare("SELECT * FROM orders WHERE id=?").get(afterHistory.orderId);db.exec("CREATE TRIGGER force_status_insert_failure BEFORE INSERT ON orders BEGIN SELECT RAISE(ABORT, 'forced'); END;");assert.throws(()=>createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now}), (e:unknown)=>e instanceof GoalFitPaymentOrderError&&e.code==="ORDER_CREATE_FAILED");db.exec("DROP TRIGGER force_status_insert_failure");assert.deepEqual(db.prepare("SELECT * FROM orders WHERE id=?").get(afterHistory.orderId),old);assert.equal(count(),3);const recovered=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:a,now});assert.equal(recovered.reused,false);assert.equal(count(),4);console.log("Goal Fit miniapp payment order status tests passed.")// Independent historical-order priority matrix using real service-created rows.
const originalConsole={log:console.log,info:console.info,warn:console.warn,error:console.error};const output:string[]=[];const capture=(...v:unknown[])=>output.push(v.map(String).join(" "));console.log=capture;console.info=capture;console.warn=capture;console.error=capture;
function matrixAssessment(key:string){const aid=`asm_matrix_${key}`,sid=`rpt_matrix_${key}`;db.prepare("INSERT INTO assessments (assessment_id,platform_identity_id,visitor_id,submission_id,target_company,target_role,question_set_version,question_bank_hash,scoring_version,payload_ciphertext,payload_hash,status,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(aid,i,"visitor","sub_"+key,"D","PM","q","h","s","TEST_PAYLOAD_CIPHERTEXT_SECRET","hash","completed",now.toISOString(),now.toISOString(),now.toISOString());const x=db.prepare("SELECT id FROM assessments WHERE assessment_id=?").get(aid) as any;db.prepare("INSERT INTO report_snapshots (report_snapshot_id,assessment_row_id,report_version,free_result_json,full_report_ciphertext,full_report_hash,created_at) VALUES (?,?,?,?,?,?,?)").run(sid,x.id,"v","{}","TEST_FULL_REPORT_CIPHERTEXT_SECRET","TEST_FULL_REPORT_HASH_SECRET",now.toISOString());return {aid,sid}}
function make(key:string,status:"pending"|"paid"|"failed"|"closed"|"expired",expired=false){const z=matrixAssessment(key);const o=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:z.aid,now});db.prepare("UPDATE orders SET status=?, expiresAt=?, createdAt=? WHERE id=?").run(status,expired?now.toISOString():o.expiresAt,new Date(now.getTime()+(status==="paid"?-10000:0)).toISOString(),o.orderId);return {...z,orderId:o.orderId}}
function purchased(z:{aid:string}){assert.throws(()=>createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:z.aid,now}),(e:unknown)=>e instanceof GoalFitPaymentOrderError&&e.code==="ALREADY_PURCHASED")}
const paidOnly=make("paid_only","paid");const paidCount=count();purchased(paidOnly);assert.equal(count(),paidCount);for(const status of ["failed","closed"] as const){const z=make("active_"+status,"pending");const h=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:z.aid,now});db.prepare("UPDATE orders SET status=? WHERE id<>? AND assessmentId=?").run(status,h.orderId,z.aid);assert.equal(createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:z.aid,now}).reused,true)}
for(const status of ["failed","closed"] as const){const z=make("expired_"+status,"pending",true);const h=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:z.aid,now});db.prepare("UPDATE orders SET status=? WHERE id<>? AND assessmentId=?").run(status,h.orderId,z.aid);db.prepare("UPDATE orders SET expiresAt=? WHERE id=?").run(now.toISOString(),h.orderId);const r=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:z.aid,now});assert.equal(r.reused,false);assert.equal((db.prepare("SELECT status FROM orders WHERE id=?").get(h.orderId) as any).status,"expired")}
const multi=make("multi","failed");const more=createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:multi.aid,now});db.prepare("UPDATE orders SET status='closed' WHERE id=?").run(more.orderId);const beforeMulti=count();assert.equal(createOrReuseGoalFitPaymentOrder({platformIdentityId:i,assessmentId:multi.aid,now}).reused,false);assert.equal(count(),beforeMulti+1);
for(const line of output)for(const secret of ["TEST_OPENID_SECRET","TEST_SESSION_TOKEN_SECRET","TEST_AUTHORIZATION_SECRET","TEST_ANSWER_SECRET","TEST_FULL_REPORT_SECRET","TEST_FULL_REPORT_CIPHERTEXT_SECRET","TEST_FULL_REPORT_HASH_SECRET","TEST_PAYLOAD_CIPHERTEXT_SECRET","TEST_SQLITE_ERROR_SECRET","TEST_ENCRYPTION_KEY_SECRET"])assert.equal(line.includes(secret),false);console.log=originalConsole.log;console.info=originalConsole.info;console.warn=originalConsole.warn;console.error=originalConsole.error;}finally{db.close();for(const s of ["","-wal","-shm"])fs.rmSync(`${databasePath}${s}`,{force:true})}